version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    commit-message:
      prefix: build
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns:
          - "*"
